package: yform_ui
version: "1.0.2"
name: YForm UI
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/yform_ui

requires:
    redaxo: ^5.13.0
    php:
        version: '>=8.0'

page:
    title: YForm UI
    perm: admin
    icon: rex-icon fa-th
    subpages:
        settings: { title: translate:settings }
        help: { title: translate:help, subPath: README.md, icon: rex-icon fa-question-circle, itemclass: pull-right }

load: early
