package: yform_ui
version: "0.0.1-dev"
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/yform_ui

requires:
    redaxo: ^5.12.0
    php:
        version: '>=7.1'

load: early
